[build]
    functions = "functions"
[dev]
    framework="gridsome"
    command = "gridsome develop" # Command to start your dev server
    port= 3850
    publish = "dist" # The path to your static content folder
    autoLaunch = true # a Boolean value that determines if Netlify Dev launches the local server address in your browser